<Project>
  <PropertyGroup Condition="'$(MSBuildProjectName)' == 'Sobakasu.Compiler.Standalone'">
    <BaseIntermediateOutputPath>obj/Sobakasu.Compiler.Standalone/</BaseIntermediateOutputPath>
    <MSBuildProjectExtensionsPath>obj/Sobakasu.Compiler/</MSBuildProjectExtensionsPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(MSBuildProjectName)' == 'Sobakasu.Compiler.Standalone.Tests'">
    <BaseIntermediateOutputPath>obj/Sobakasu.Compiler.Standalone.Tests/</BaseIntermediateOutputPath>
    <MSBuildProjectExtensionsPath>obj/Sobakasu.Compiler.Tests/</MSBuildProjectExtensionsPath>
  </PropertyGroup>
</Project>
