namespace Skytomo221.Sobakasu.Compiler.Syntax
{
  public enum SyntaxKind
  {
    On,
    LetKeyword,
    MutKeyword,
    TrueKeyword,
    FalseKeyword,
    NullKeyword,
    U0Keyword,
    Identifier,
    Int8Literal,
    UInt8Literal,
    Int16Literal,
    UInt16Literal,
    Int32Literal,
    UInt32Literal,
    Int64Literal,
    UInt64Literal,
    Float32Literal,
    Float64Literal,
    CharacterLiteral,
    String,
    Dot,
    Comma,
    Colon,
    Equals,
    LeftBrace,
    RightBrace,
    LeftParen,
    RightParen,
    LeftBracket,
    RightBracket,
    Semicolon,
    EndOfFile,
    BadToken
  }
}
